#!/usr/bin/env bash
# Regenerate THIRD_PARTY_LICENSES.md: the license notices of every crate that ends up inside the
# frameeyeosc binary or the bundled eyecam binaries (tools/eyecam; build-time-only proc-macro crates
# are left out), of the OpenVR header that frameeyeosc-panel is built with, and eyecam's NOTICE for
# the code it ports. For crates offered under a choice of licenses, the MIT text is reproduced.
set -euo pipefail
cd "$(dirname "$0")/.."

cargo="${CARGO:-cargo}"
command -v "$cargo" >/dev/null || cargo="$HOME/.cargo/bin/cargo"
rustc="${RUSTC:-rustc}"
command -v "$rustc" >/dev/null || rustc="$HOME/.cargo/bin/rustc"
rust_mit="$("$rustc" --print sysroot)/share/doc/rust/licenses/MIT.txt"
registry="${CARGO_HOME:-$HOME/.cargo}/registry/src"
out=THIRD_PARTY_LICENSES.md
openvr_license=panel/third_party/openvr/LICENSE
openvr_header=panel/third_party/openvr/openvr.h
openvr_version="$(sed -n 's/.*k_nSteamVRVersion[A-Za-z]* = \([0-9]*\);.*/\1/p' "$openvr_header" | paste -sd.)"

eyecam_notice=tools/eyecam/NOTICE

crates="$(for manifest in Cargo.toml tools/eyecam/Cargo.toml; do
    "$cargo" tree --manifest-path "$manifest" --offline --locked --target aarch64-unknown-linux-gnu \
        -e normal,no-proc-macro --prefix none --format '{p}|{l}'
done | grep -v -e '(proc-macro)' -e '(\*)' -e '^frameeyeosc ' -e '^eyecam ' | sort -u)"

{
    echo "# Third-party licenses"
    echo
    echo "Third-party code included in frameeyeosc, frameeyeosc-panel and the bundled eye-camera tool"
    echo "eyecam (eyecam-rec and eyecam-grab, from tools/eyecam). frameeyeosc and eyecam include the Rust"
    echo "standard library and the Rust crates below; frameeyeosc-panel is built with the OpenVR SDK header;"
    echo "eyecam ports parts of FrameEyeCameraFeed. Their license notices follow."
    echo
    echo "frameeyeosc-panel also links at run time to libraries that come with SteamOS and SteamVR (cairo,"
    echo "FreeType, the Vulkan loader, libopenvr_api). They are not bundled, so they are not listed here."
    echo
    echo "vendor/frame-updater/ (the update checker in frameeyeosc-panel and frame-update.sh) is not"
    echo "third-party code: it is the author's (sasaken1102r's) own, under the same MIT license as this"
    echo "repository, so it is not listed below."
    echo
    echo "This file is generated by scripts/third-party-licenses.sh."
    echo
    while IFS='|' read -r pkg license; do
        name="${pkg%% *}"
        version="${pkg#* v}"
        dir="$(find "$registry" -maxdepth 2 -type d -name "$name-$version" | head -n 1)"
        file=""
        for candidate in LICENSE-MIT LICENSE_MIT LICENSE-MIT.md LICENSE LICENSE.md; do
            if [[ -f "$dir/$candidate" ]]; then file="$dir/$candidate"; break; fi
        done
        if [[ -z "$file" ]]; then
            echo "No license file found for $name $version" >&2
            exit 1
        fi
        echo "## $name $version"
        echo
        echo "License: $license"
        echo
        echo '```'
        sed 's/\r$//' "$file"
        echo '```'
        echo
    done <<<"$crates"
    echo "## Rust standard library"
    echo
    echo "License: MIT OR Apache-2.0. Per-component notices are in the COPYRIGHT file of the Rust"
    echo "project (https://github.com/rust-lang/rust/blob/master/COPYRIGHT)."
    echo
    echo '```'
    sed -e 's/\r$//' -e 's/<year> <copyright holders>/The Rust Project Contributors/' "$rust_mit"
    echo '```'
    echo
    echo "## OpenVR SDK $openvr_version (openvr.h)"
    echo
    echo "License: BSD-3-Clause. frameeyeosc-panel is built with this header (panel/third_party/openvr)."
    echo
    echo '```'
    sed 's/\r$//' "$openvr_license"
    echo '```'
    echo
    echo "## FrameEyeCameraFeed (ported in eyecam)"
    echo
    echo "License: MIT. eyecam's notice (tools/eyecam/NOTICE, also in the release tarball as eyecam/NOTICE):"
    echo
    echo '```'
    sed 's/\r$//' "$eyecam_notice"
    echo '```'
} >"$out"
echo "$out"
